version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    rebase-strategy: auto
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
